spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: qqq
          uri: https://www.qq.com
          predicates:
            - Query=url, qq