spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GBGFQKtfsJLehCMSJkK
      secret-key: aKO82Nsqi1wjBlUcoGmHilBaTuPjHi
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-itzhouq

server:
  port: 30000
